// Detailed descriptions for each aroma label. The keys correspond
// exactly to labels defined in the aromatlas. Each entry lists
// chemical families, typical compounds, production origins and
// tasting tips. Unknown values are represented by dashes (—).

export default {
  "banane": {classe:"Esters (acétates)", composés:"Acétate d’isoamyle", origine:"Fermentation longue et chaude favorisant les esters fruités ; reflux doux à la distillation.", fut:"Fûts bourbon 1er remplissage préservent ces esters ; trop d’extraction peut les estomper.", tips:"Très fréquent dans certains single malts non tourbés.", styles:"Irish Pot Still, Speyside jeune."},
  "pomme": {classe:"Esters (hexanoates/acétates)", composés:"Hexanoate d’éthyle, acétate d’éthyle", origine:"Levures produisant acides gras + éthanol ⇒ esters ; têtes larges accentuent l’acétate.", fut:"Refill bourbon conserve la verdeur.", tips:"S’apaise avec l’oxydation ; revient avec un trait d’eau.", styles:"Lowlands, Speyside légers."},
  "poire": {classe:"Esters", composés:"Acétate d’hexyle, butyrate d’éthyle", origine:"Fermentation à basse T°, levures très estérifiantes.", fut:"Refill bourbon ; certains vins doux renforcent la poire.", tips:"Très volatil : ressenti surtout au nez.", styles:"Speyside, Irish"},
  "ananas": {classe:"Esters", composés:"Butyrate/hexanoate d’éthyle", origine:"Fermentation riche en acides gras ; distillation avec reflux.", fut:"Bourbon & ex-rum finish amplifient.", tips:"Avec noix de coco (lactones) ⇒ ‘pina colada’.", styles:"Highlands fruités"},
  "citron": {classe:"Terpènes / Aldéhydes", composés:"Limonène, citral", origine:"Congénères légers captés en têtes ; distillation propre.", fut:"Refill/fort toast pour garder la vivacité.", tips:"Parfois avec ‘pierre à fusil’.", styles:"Maritime, Highlands"},
  "lavande": {classe:"Terpènes", composés:"Linalol", origine:"Fermentation ‘propre’, distillation douce.", fut:"Refill bourbon, sherry masque souvent ces notes.", tips:"Fragile à l’oxydation en verre.", styles:"Speyside"},
  "menthe": {classe:"Terpènes / Phénols légers", composés:"Menthol, eucalyptol", origine:"Reflux + coupe serrée.", fut:"American oak → ‘menthe-chocolat’ avec cacao/furfural.", tips:"Sensation fraîche.", styles:"Bourbon cask"},
  "chocolat": {classe:"Furannes / Pyrazines", composés:"5-Méthylfurfural, pyrazines", origine:"Toast/char élevé ; Maillard des douelles.", fut:"American oak fortement bousiné ; rechar/STR.", tips:"Souvent avec café/cacao/biscuit.", styles:"Sherry butt, STR"},
  "biscuit": {classe:"Maillard", composés:"Maltol, cyclotène", origine:"Kilning/concassage ; distillation peu réductrice.", fut:"Bourbon cask, toasts moyens.", tips:"Texture maltée.", styles:"Highlands"},
  "fumé": {classe:"Phénols", composés:"Gaïacol, crésols, syringol", origine:"Malt séché à la tourbe ; ppm + coupe ‘cœur’ = intensité.", fut:"Rechar → fumé-sucré ; refill atténue.", tips:"Fumée sèche (gaïacol) vs médicinal (p-crésol).", styles:"Islay, Orkney"},
  "tourbe": {classe:"Phénols / Terpènes", composés:"Crésols, phénol, 4-éthylgaïacol", origine:"Kilning tourbé ; distillation courte/huileuse.", fut:"Refill pour pureté ; sherry = tourbe ‘gourmande’.", tips:"Persistance rétro-olfactive longue.", styles:"Islay, peated Highlands"},
  "médicinal": {classe:"Phénols", composés:"p-Crésol, gaïacol", origine:"Tourbe côtière + worm tub ⇒ notes lourdes.", fut:"Refill maintient l’aspect hôpital ; sherry arrondit.", tips:"Souvent indice de coupe légèrement basse.", styles:"South Islay"},
  "vanille": {classe:"Aldéhydes phénoliques", composés:"Vanilline", origine:"Dégradation lignine (chauffe du chêne).", fut:"Quercus alba 1er remplissage = boost vanille.", tips:"Adoucit et arrondit.", styles:"Bourbon cask & bourbon"},
  "caramel": {classe:"Furannes", composés:"Furfural, HMF", origine:"Toast/char ; Maillard des sucres.", fut:"Rechar/char élevé.", tips:"Peut virer ‘brûlé’ si sur-extraction.", styles:"Bourbon & sherry"},
  "noix de coco": {classe:"Lactones", composés:"β-methyl-γ-octalactone (cis/trans)", origine:"Chêne américain riche en lactones.", fut:"Bourbon 1er remplissage = coco/crème.", tips:"Avec ananas ⇒ pina colada.", styles:"Bourbon cask"},
  "cannelle": {classe:"Aldéhydes / Phénols épicés", composés:"Cinnamaldéhyde, eugénol", origine:"Chêne européen + toast modéré.", fut:"Sherry butt/hogshead européens.", tips:"Épice sèche en finale.", styles:"Sherry cask"},
  "noix": {classe:"Aldéhydes oxydatifs", composés:"Acétaldéhyde, sotolon", origine:"Maturation oxydative (sherry) ; long vieillissement.", fut:"Oloroso/PX ⇒ fruits secs & noix.", tips:"Rancio si très âgé.", styles:"Sherry matured"},
  // Fallback entries for notes without specific data. Dashes signify unknown information.
  "citron vert": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "orange": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "mandarine": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "pamplemousse": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "mangue": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "papaye": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "fruit de la passion": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "melon": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "pomme verte": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "coing": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "pêche": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "abricot": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "prune": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "mirabelle": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "fraise": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "framboise": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "cassis": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "mûre": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "myrtille": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "raisin sec": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "pruneau": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "figue sèche": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "abricot sec": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "dattes": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "fleur d’oranger": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "rose": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "bruyère": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "géranium": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "violette": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "herbe coupée": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "eucalyptus": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "genévrier": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "feuille de tabac": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "foin": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "thym": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "pin": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "toast": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "café": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "cacao": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "pain frais": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "pâte levée": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "brioche": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "yaourt/fromage frais": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "huile minérale": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "cire de bougie / paraffine": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "beurre rance": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "savon": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "métallique": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "cuir": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "sac de jute": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "terre humide": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "mousse d’arbre": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "vieux bandage": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "bacon": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "goudron": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "caoutchouc": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "kérosène": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "silex": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "poisson / fruits de mer": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "iode": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "algue": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "soufre": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "chêne": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "cèdre": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "bois de santal": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "miel": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "girofle": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "gingembre": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "poivre": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "noix de muscade": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "cardamome": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "sherry / xérès": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "madère": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "porto": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "vin rouge": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "sauternes": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "noisette": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "amande": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "pralin": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"},
  "nougat": {classe:"—", composés:"—", origine:"—", fut:"—", tips:"—", styles:"—"}
};
